version: "2"

services:
  nginx:
    image: nginx:latest
    links: [ api ]
    ports: [ "3000:80" ]
    volumes:
      - ./config/nginx.dev.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  minio:
    image: minio/minio
    command: ["server", "/uploads"]
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: 9ESMOOGV83RDO23UOHJ5
      MINIO_SECRET_KEY: yz/3DF2E1dekuFqqY0HpAGOxxDjCda8KAMwYwah5
    ports:
      # - "127.0.0.1:9000:9000"
      - "0.0.0.0:9000:9000"
    volumes:
      - "./uploads:/uploads"

  api:
    build: .
    container_name: api
    environment:
      DB_HOST: postgres
      DB_USER: saas
      DB_PASSWORD: password
      REDIS_HOST: redis
      S3_ENDPOINT: minio
      S3_BUCKET: saas-pub-cdn
      S3_PORT: 9000
      TS_NODE_FILES: "true"
    links:
      - postgres
      - redis
    volumes:
      - ".:/code"
      - "/code/node_modules"
