version: "2"

services:
  saas.postgres:
    image: postgres:9.6-alpine
    container_name: saas.postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"

  saas.redis:
    image: redis
    container_name: saas.redis
    ports:
      - "127.0.0.1:6379:6379"

  saas.minio:
    image: minio/minio
    command: ["server", "/uploads"]
    container_name: saas.minio
    environment:
      MINIO_ACCESS_KEY: 9ESMOOGV83RDO23UOHJ5
      MINIO_SECRET_KEY: yz/3DF2E1dekuFqqY0HpAGOxxDjCda8KAMwYwah5
    ports:
      # - "127.0.0.1:9000:9000"
      - "0.0.0.0:9000:9000"
    volumes:
      - "./uploads:/uploads"

  saas.api:
    build: .
    container_name: saas.api
    command: ["yarn", "start"]
    environment:
      DB_HOST: saas.postgres
      REDIS_HOST: saas.redis
      S3_ENDPOINT: saas.minio
      S3_PORT: 9000
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - saas.postgres
      - saas.redis
    volumes:
      - ".:/code"
      - "/code/node_modules"
