export const VISIBILITY_PUBLIC = "PUBLIC"
export const VISIBILITY_PRIVATE = "PRIVATE"

export const GAME_STATUS_CREATED = "CREATED"
export const GAME_STATUS_STARTED = "STARTED"
export const GAME_STATUS_IN_PROGRESS = "IN_PROGRESS"
export const GAME_STATUS_RESTARTED = "RESTARTED"
export const GAME_STATUS_STOPPED = "STOPPED"
export const GAME_STATUS_COMPLETED = "COMPLETED"

export const MEDAL_TIER_BRONZE = "TIER_BRONZE"
export const MEDAL_TIER_SILVER = "TIER_SILVER"
export const MEDAL_TIER_GOLD = "TIER_GOLD"
export const MEDAL_TIER_PLATINUM = "TIER_PLATINUM"
export const MEDAL_TIER_ONYX = "TIER_ONYX"

export const SPAWN_STRATEGY_RANDOM = "RANDOM"
export const SPAWN_STRATEGY_STATIC = "STATIC"
export const SPAWN_STRATEGY_DONT_RESPAWN = "DONT_RESPAWN"
